version: '2.1'

services:
  wait-for-startup:
    command: /bin/echo bar Started
    image: alpine
    depends_on:
          bar-api:
            condition: service_healthy

  bar-api:
    image: docker.artifactory.reform.hmcts.net/bar/bar-api:${BAR_API_DOCKER_VERSION:-latest}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bar-database:5432/bar
      - SPRING_DATASOURCE_USERNAME=bar
      - SPRING_DATASOURCE_PASSWORD=bar
      - AUTH_IDAM_CLIENT_BASEURL=http://idam-api:8080
      - ROOT_APPENDER=JSON_CONSOLE
    ports:
      - 4411:8080
    depends_on:
       bar-database:
           condition: service_started

  bar-database:
    image: docker.artifactory.reform.hmcts.net/bar/bar-database:${BAR_DATABASE_DOCKER_VERSION:-latest}
    environment:
      - BAR_DB_USERNAME=bar
      - BAR_DB_PASSWORD=bar

